# This override is used automatically by `docker compose up` for local development.
# It bind-mounts source code so changes are reflected immediately without rebuilds
# and enables Flask debug/reloader.
services:
  # Use MySQL 8.0 for local development (ARM64 compatible)
  # while keeping MySQL 5.7 in the main compose for server compatibility
  db:
    image: mysql:8.0
    platform: linux/arm64  # Use native ARM64 on Apple Silicon
    
  # Use ARM64 version of Adminer for local development
  adminer:
    platform: linux/arm64
    
  web:
    environment:
      FLASK_DEBUG: 1
    volumes:
      # Bind mount application source (Python, templates, static)
      - ./app:/app/app
      # Optionally bind the entry point script if you edit it frequently
      # - ./scripts:/app/scripts
      # Bind the app runner so edits are picked up too
      - ./run.py:/app/run.py
